# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Inventory Service Build
on:
  push:
    branches: [ "main" ]
    paths:
      - 'SOMSystem/InventoryService/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'SOMSystem/InventoryService/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SOMSystem/InventoryService/SOM.InventoryApi/SOM.InventoryApi.csproj
    - name: Build
      run: dotnet build SOMSystem/InventoryService/SOM.InventoryApi/SOM.InventoryApi.csproj --no-restore
